### ISSUE TITLE
Get together as a team

### ISSUE THREAD

**Issue by jbwoo9779** [StanfordCS194/Team-10#1]
Hi folks,

Please arrange to meet one another, find a good SGM time that works for you and get after the [Startup Your Team](https://github.com/StanfordCS194/Home/blob/master/Startup-Your-Team.md) assignment

Jeff

**Comment by zack5** [comment]
Hi, let's get in contact! My email is icinquin@...

**Comment by AzurNova** [comment]
Hi, my email is lucaslin@ though I think communication over something like Messenger or Slack would work better. What weekly meeting time did you sign us up for?

**Comment by amberzw** [comment]
By the way, I'm also in this team, but wasn't added to this issue? My email is awollam@ but yeah, Messenger or Slack would probably be better
